name: 'ticket_service'

services:
  
  domic.ticket.api:
    networks:
      - domic
    image: ticket_service_api_image:1.0.0
    container_name: "ticket_service_api"
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3010-3020:443"
    volumes:
      - log:/app/CoreLogs
#     - ~/services/Domic-TicketService/.https/:/https/
      - C:\https\:/https/
    environment:
      - Elastic-Host=http://domic.elastic.search:9200
      - Elastic-Index=ticket
      - Elastic-Username=domic
      - Elastic-Password=Domic123!@#
      - E-RabbitMQ-Host=domic.rabbit.mq
      - E-RabbitMQ-Port=5672
      - E-RabbitMQ-Username=domic
      - E-RabbitMQ-Password=Domic123!@#
      - I-RabbitMQ-Host=
      - I-RabbitMQ-Port=
      - I-RabbitMQ-Username=
      - I-RabbitMQ-Password=
      - E-RedisConnectionString=domic.redis:6379
      - I-RedisConnectionString=domic.ticket.redis:6379
      - MongoConnectionString=
      - C-SqlServerConnectionString=Server=domic.ticket.command.sql.server,1433;Database=TicketService;User ID=sa;Password=Domic123!@#;Persist Security Info=True;MultipleActiveResultSets=True;
      - Q-SqlServerConnectionString=
      - Host=domic.ticket.api
      - Port=443
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Domic123!@#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Domic.WebAPI.pfx
    
    depends_on:
      - domic.ticket.command.sql.server
      - domic.ticket.redis
  
  domic.ticket.command.sql.server:
    networks:
      - domic
    image: 'mcr.microsoft.com/mssql/server'
    container_name: "ticket_command_sql_server"
    ports:
      - 1700:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Domic123!@#

  domic.ticket.redis:
    networks:
      - domic
    image: 'redis'
    container_name: 'ticket_redis'
    command: 'redis-server'
    ports:
      - 5555:6379

volumes:
  log:
    
networks:
  domic:
    external: true